#!/usr/bin/env python3
import os
import yaml

"""
A small script that will combine multiple yaml files into a single
multi-document yaml file. Its output is intended to be used with commands like:

    oc create -f ./all.yml
    oc get -f ./all.yml
    oc delete -f ./all.yml
"""


def main(dir_path):
    crds = get_crds(dir_path)
    print(yaml.safe_dump_all(crds))


def write_crds(obj, path):
    with open(path, 'w') as fobj:
        fobj.write(yaml.safe_dump_all(obj))
    return path


def get_crds(dir_path):
    crds = []
    for path in get_crd_paths(dir_path):
        try:
            crds.append(yaml.safe_load(open(path)))
        except yaml.composer.ComposerError:
            # If we hit this exception, it means we hit a multi-document YAML
            # file. This is almost certainly going to be one generated by this
            # very script.
            pass
    return crds


def get_crd_paths(dir_path=os.path.curdir):
    crd_paths = filter(
        lambda path: path.endswith(('.yaml', '.yml')),
        os.listdir(dir_path),
    )
    return map(lambda path: os.path.join(dir_path, path), crd_paths)


if __name__ == "__main__":
    main(os.path.curdir)
