apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-provisioner: infinibox-csi-driver
    finalizers:
    - kubernetes.io/pvc-protection
    name: grafana
    namespace: jenkim-dev
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: dynamic-nfs
    volumeMode: Filesystem
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-provisioner: infinibox-csi-driver
    finalizers:
    - kubernetes.io/pvc-protection
    name: prometheus
    namespace: jenkim-dev
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: dynamic-nfs
    volumeMode: Filesystem
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
